[package]
name = "test_app"
version = "0.7.0"
edition = "2021"
publish = false

[dependencies]
schematic = { path = "../config" }
miette = { workspace = true, features = ["fancy"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.95"
